return {
    version = 1,
    format = "json",
    data = {
        animations = {
            {
                duration = 1,
                animation_id = "default",
                animation_keys = {
                },
            },
            {
                duration = 1,
                animation_id = "spin",
                animation_keys = {
                    {
                        key_type = "tween",
                        easing = "outsine",
                        property_id = "color_a",
                        start_value = 0.8,
                        node_id = "text_value_extra",
                    },
                    {
                        key_type = "tween",
                        end_value = 3.1,
                        easing = "outsine",
                        property_id = "scale_x",
                        start_value = 3.5,
                        node_id = "text_value_extra",
                    },
                    {
                        key_type = "tween",
                        end_value = 3.1,
                        easing = "outsine",
                        property_id = "scale_y",
                        start_value = 3.5,
                        node_id = "text_value_extra",
                    },
                    {
                        key_type = "tween",
                        end_value = 4,
                        easing = "outsine",
                        property_id = "scale_x",
                        start_value = 3.7,
                        node_id = "text_value",
                    },
                    {
                        key_type = "tween",
                        end_value = 4,
                        easing = "outsine",
                        property_id = "scale_y",
                        start_value = 3.7,
                        node_id = "text_value",
                    },
                    {
                        key_type = "tween",
                        end_value = -180,
                        easing = "linear",
                        property_id = "position_y",
                        duration = 0.5,
                        start_value = -130,
                        node_id = "text_value_down",
                    },
                    {
                        key_type = "tween",
                        end_value = -60,
                        easing = "linear",
                        property_id = "rotation_x",
                        duration = 0.5,
                        start_value = -40,
                        node_id = "text_value_down",
                    },
                    {
                        key_type = "tween",
                        easing = "linear",
                        property_id = "color_a",
                        duration = 0.5,
                        start_value = 0.8,
                        node_id = "text_value_down",
                    },
                    {
                        key_type = "tween",
                        end_value = 3.1,
                        easing = "outsine",
                        property_id = "scale_x",
                        duration = 0.5,
                        start_value = 3.5,
                        node_id = "text_value_down",
                    },
                    {
                        key_type = "tween",
                        end_value = 3.1,
                        easing = "outsine",
                        property_id = "scale_y",
                        duration = 0.5,
                        start_value = 3.5,
                        node_id = "text_value_down",
                    },
                    {
                        key_type = "tween",
                        end_value = -130,
                        easing = "linear",
                        property_id = "position_y",
                        duration = 1,
                        node_id = "text_value",
                    },
                    {
                        key_type = "tween",
                        easing = "linear",
                        property_id = "position_y",
                        duration = 1,
                        start_value = 130,
                        node_id = "text_value_up",
                    },
                    {
                        key_type = "tween",
                        end_value = -40,
                        easing = "linear",
                        property_id = "rotation_x",
                        duration = 1,
                        node_id = "text_value",
                    },
                    {
                        key_type = "tween",
                        easing = "linear",
                        property_id = "rotation_x",
                        duration = 1,
                        start_value = 40,
                        node_id = "text_value_up",
                    },
                    {
                        key_type = "tween",
                        end_value = 0.8,
                        easing = "linear",
                        property_id = "color_a",
                        duration = 1,
                        start_value = 1,
                        node_id = "text_value",
                    },
                    {
                        key_type = "tween",
                        end_value = 1,
                        easing = "linear",
                        property_id = "color_a",
                        duration = 1,
                        start_value = 0.8,
                        node_id = "text_value_up",
                    },
                    {
                        key_type = "tween",
                        end_value = 3.5,
                        easing = "linear",
                        property_id = "scale_x",
                        duration = 1,
                        start_value = 4,
                        node_id = "text_value",
                    },
                    {
                        key_type = "tween",
                        end_value = 3.5,
                        easing = "linear",
                        property_id = "scale_y",
                        duration = 1,
                        start_value = 4,
                        node_id = "text_value",
                    },
                    {
                        key_type = "tween",
                        end_value = 4,
                        easing = "linear",
                        property_id = "scale_x",
                        duration = 1,
                        start_value = 3.5,
                        node_id = "text_value_up",
                    },
                    {
                        key_type = "tween",
                        end_value = 4,
                        easing = "linear",
                        property_id = "scale_y",
                        duration = 1,
                        start_value = 3.5,
                        node_id = "text_value_up",
                    },
                    {
                        key_type = "tween",
                        end_value = 130,
                        easing = "linear",
                        start_value = 180,
                        property_id = "position_y",
                        duration = 0.5,
                        start_time = 0.5,
                        node_id = "text_value_extra",
                    },
                    {
                        key_type = "tween",
                        end_value = 0.8,
                        easing = "linear",
                        property_id = "color_a",
                        duration = 0.5,
                        start_time = 0.5,
                        node_id = "text_value_extra",
                    },
                    {
                        key_type = "tween",
                        end_value = 3.5,
                        easing = "outsine",
                        start_value = 3.1,
                        property_id = "scale_x",
                        duration = 0.5,
                        start_time = 0.5,
                        node_id = "text_value_extra",
                    },
                    {
                        key_type = "tween",
                        end_value = 3.5,
                        easing = "outsine",
                        start_value = 3.1,
                        property_id = "scale_y",
                        duration = 0.5,
                        start_time = 0.5,
                        node_id = "text_value_extra",
                    },
                    {
                        key_type = "tween",
                        end_value = 40,
                        easing = "linear",
                        start_value = 90,
                        property_id = "rotation_x",
                        duration = 0.5,
                        start_time = 0.5,
                        node_id = "text_value_extra",
                    },
                },
            },
            {
                duration = 4,
                animation_id = "preview",
                animation_keys = {
                    {
                        key_type = "animation",
                        easing = "linear",
                        property_id = "on_start_spin",
                        duration = 0.4,
                        data = "on_start_spin",
                    },
                    {
                        key_type = "animation",
                        start_time = 0.4,
                        easing = "outsine",
                        property_id = "spin",
                        duration = 0.27,
                        data = "spin",
                    },
                    {
                        key_type = "animation",
                        start_time = 0.67,
                        easing = "outsine",
                        property_id = "spin",
                        duration = 0.27,
                        data = "spin",
                    },
                    {
                        key_type = "animation",
                        start_time = 0.93,
                        easing = "outsine",
                        property_id = "spin",
                        duration = 0.27,
                        data = "spin",
                    },
                    {
                        key_type = "animation",
                        start_time = 1.12,
                        easing = "linear",
                        property_id = "on_end_spin",
                        duration = 0.78,
                        data = "on_end_spin",
                    },
                },
            },
            {
                duration = 0.4,
                animation_id = "on_start_spin",
                animation_keys = {
                    {
                        key_type = "tween",
                        end_value = 1.3,
                        easing = "outsine",
                        property_id = "color_a",
                        duration = 0.1,
                        start_value = 1,
                        node_id = "gradient",
                    },
                    {
                        key_type = "tween",
                        end_value = 1.3,
                        easing = "outsine",
                        property_id = "color_a",
                        duration = 0.1,
                        start_value = 1,
                        node_id = "outline",
                    },
                    {
                        key_type = "event",
                        start_time = 0.1,
                        easing = "outsine",
                        property_id = "event",
                        data = "any_data",
                        event_id = "test_event",
                    },
                    {
                        key_type = "tween",
                        end_value = 1,
                        easing = "insine",
                        start_value = 1.3,
                        property_id = "color_a",
                        duration = 0.3,
                        start_time = 0.1,
                        node_id = "gradient",
                    },
                    {
                        key_type = "tween",
                        end_value = 1,
                        easing = "insine",
                        start_value = 1.3,
                        property_id = "color_a",
                        duration = 0.3,
                        start_time = 0.1,
                        node_id = "outline",
                    },
                },
            },
            {
                duration = 1,
                animation_id = "on_end_spin",
                animation_keys = {
                    {
                        key_type = "tween",
                        end_value = 1.4,
                        easing = "outsine",
                        property_id = "color_a",
                        duration = 0.25,
                        start_value = 1,
                        node_id = "gradient",
                    },
                    {
                        key_type = "tween",
                        end_value = 3,
                        easing = "outsine",
                        property_id = "scale_x",
                        duration = 0.25,
                        start_value = 3.5,
                        node_id = "text_value_down",
                    },
                    {
                        key_type = "tween",
                        end_value = 3,
                        easing = "outsine",
                        property_id = "scale_y",
                        duration = 0.25,
                        start_value = 3.5,
                        node_id = "text_value_down",
                    },
                    {
                        key_type = "tween",
                        end_value = 3,
                        easing = "outsine",
                        property_id = "scale_x",
                        duration = 0.25,
                        start_value = 3.5,
                        node_id = "text_value_up",
                    },
                    {
                        key_type = "tween",
                        end_value = 3,
                        easing = "outsine",
                        property_id = "scale_y",
                        duration = 0.25,
                        start_value = 3.5,
                        node_id = "text_value_up",
                    },
                    {
                        key_type = "tween",
                        end_value = 4.6,
                        easing = "outsine",
                        property_id = "scale_x",
                        duration = 0.25,
                        start_value = 3.7,
                        node_id = "text_value",
                    },
                    {
                        key_type = "tween",
                        end_value = 4.6,
                        easing = "outsine",
                        property_id = "scale_y",
                        duration = 0.25,
                        start_value = 3.7,
                        node_id = "text_value",
                    },
                    {
                        key_type = "tween",
                        end_value = 8,
                        easing = "outsine",
                        property_id = "rotation_z",
                        duration = 0.25,
                        node_id = "text_value",
                    },
                    {
                        key_type = "tween",
                        start_time = 0.25,
                        easing = "insine",
                        property_id = "rotation_z",
                        duration = 0.42,
                        start_value = 8,
                        node_id = "text_value",
                    },
                    {
                        key_type = "tween",
                        end_value = 3.7,
                        easing = "insine",
                        start_value = 4.6,
                        property_id = "scale_x",
                        duration = 0.32,
                        start_time = 0.35,
                        node_id = "text_value",
                    },
                    {
                        key_type = "tween",
                        end_value = 3.7,
                        easing = "insine",
                        start_value = 4.6,
                        property_id = "scale_y",
                        duration = 0.32,
                        start_time = 0.35,
                        node_id = "text_value",
                    },
                    {
                        key_type = "tween",
                        end_value = 1,
                        easing = "outsine",
                        start_value = 1.4,
                        property_id = "color_a",
                        duration = 0.2,
                        start_time = 0.4,
                        node_id = "gradient",
                    },
                    {
                        key_type = "tween",
                        end_value = 3.5,
                        easing = "outsine",
                        start_value = 3,
                        property_id = "scale_x",
                        duration = 0.35,
                        start_time = 0.45,
                        node_id = "text_value_down",
                    },
                    {
                        key_type = "tween",
                        end_value = 3.5,
                        easing = "outsine",
                        start_value = 3,
                        property_id = "scale_y",
                        duration = 0.35,
                        start_time = 0.45,
                        node_id = "text_value_down",
                    },
                    {
                        key_type = "tween",
                        end_value = 3.5,
                        easing = "outsine",
                        start_value = 3,
                        property_id = "scale_x",
                        duration = 0.35,
                        start_time = 0.45,
                        node_id = "text_value_up",
                    },
                    {
                        key_type = "tween",
                        end_value = 3.5,
                        easing = "outsine",
                        start_value = 3,
                        property_id = "scale_y",
                        duration = 0.35,
                        start_time = 0.45,
                        node_id = "text_value_up",
                    },
                },
            },
        },
        nodes = {
        },
        metadata = {
            settings = {
                font_size = 30,
            },
            gizmo_steps = {
            },
            fps = 60,
            layers = {
            },
            gui_path = "/example_window/ui_spin_slot/ui_spin_slot.gui",
        },
    },
    type = "animation_editor",
}