return {
    type = "animation_editor",
    format = "json",
    version = 1,
    data = {
        metadata = {
            gizmo_steps = {
            },
            gui_path = "/example_basic/example_basic.gui",
            fps = 60,
            layers = {
            },
            settings = {
                font_size = 40,
            },
        },
        nodes = {
        },
        animations = {
            {
                duration = 1,
                animation_id = "default",
                animation_keys = {
                    {
                        start_value = 2,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "image",
                        end_value = 3,
                        duration = 0.28,
                        property_id = "scale_x",
                    },
                    {
                        start_value = 2,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "image",
                        end_value = 3,
                        duration = 0.28,
                        property_id = "scale_y",
                    },
                    {
                        start_value = 1,
                        easing = "outsine",
                        end_value = 0.33,
                        key_type = "tween",
                        start_time = 0.28,
                        node_id = "image",
                        duration = 0.47,
                        property_id = "color_b",
                    },
                    {
                        start_value = 1,
                        easing = "outsine",
                        end_value = 0.33,
                        key_type = "tween",
                        start_time = 0.28,
                        node_id = "image",
                        duration = 0.47,
                        property_id = "color_g",
                    },
                    {
                        start_value = 1,
                        easing = "outsine",
                        end_value = 0.89,
                        key_type = "tween",
                        start_time = 0.28,
                        node_id = "image",
                        duration = 0.47,
                        property_id = "color_r",
                    },
                    {
                        end_value = 360,
                        easing = "outsine",
                        key_type = "tween",
                        start_time = 0.28,
                        duration = 0.47,
                        node_id = "image",
                        property_id = "rotation_z",
                    },
                    {
                        start_value = 3,
                        easing = "outback",
                        end_value = 2,
                        key_type = "tween",
                        start_time = 0.75,
                        node_id = "image",
                        duration = 0.25,
                        property_id = "scale_x",
                    },
                    {
                        start_value = 3,
                        easing = "outback",
                        end_value = 2,
                        key_type = "tween",
                        start_time = 0.75,
                        node_id = "image",
                        duration = 0.25,
                        property_id = "scale_y",
                    },
                    {
                        start_value = 0.33,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        start_time = 0.79,
                        node_id = "image",
                        duration = 0.14,
                        property_id = "color_b",
                    },
                    {
                        start_value = 0.33,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        start_time = 0.79,
                        node_id = "image",
                        duration = 0.14,
                        property_id = "color_g",
                    },
                    {
                        start_value = 0.89,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        start_time = 0.79,
                        node_id = "image",
                        duration = 0.14,
                        property_id = "color_r",
                    },
                },
            },
        },
    },
}